# Header
menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/leVirve
rss: /atom.xml

# Content
excerpt_link: 閱讀全文
fancybox: true

# Sidebar
sidebar: true
widgets:
- tag
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-82808777-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
